name: Make on push

on:
  push:
    paths:
      - csv/*
      - meta/*
      - json/*
      - SKK-JISYO.*
      - zipcode/SKK-JISYO.*

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install packages
      run: |
        sudo apt update
        sudo apt -y install autoconf docdiff emacs nkf libdb-dev

    - name: clone skktools
      uses: actions/checkout@v4
      with:
        repository: skk-dev/skktools
        path: tools
    - name: make skktools
      run: |
        cd tools
        ./configure
        make
        pwd >> $GITHUB_PATH

    - name: install deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        path: dict

    - name: make -C zipcode
      run: |
        cd dict
        cd zipcode
        autoconf -f
        ./configure
        make batch test

    - name: make
      run: |
        cd dict
        make MD5=md5sum gzip

    - name: prepare git user
      run: |
        cd dict
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: push ChangeLog for the previous commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd dict
        git log HEAD^..HEAD --name-only --oneline \
        | grep ^ChangeLog || \
        git log HEAD^..HEAD --name-only --oneline \
        | grep SKK-JISYO | grep -v json | grep -v edict2 && \
        env COMPARED='HEAD^..HEAD' \
          USERNAME='${{ github.event.head_commit.author.name }}' \
          USEREMAIL='${{ github.event.head_commit.author.email }}' \
          sh script/manued.sh \
        | tee headlog.txt && \
        (cat headlog.txt ChangeLog > ChangeLog.tmp && mv ChangeLog{.tmp,}) && \
        git add ChangeLog && \
        printf "auto-push ChangeLog\n\n" \
        | cat - headlog.txt \
        | git commit -F - && \
        git push

    - name: auto-push after make
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd dict
        git diff --no-prefix -I '^;' | sed -n 's/^--- //p' \
        | grep SKK-JISYO \
        | grep -v json | grep -v edict2 | grep -v ivd && \
        env COMPARED='HEAD' \
          USERNAME='${{ github.event.head_commit.author.name }}' \
          USEREMAIL='${{ github.event.head_commit.author.email }}' \
          sh script/manued.sh \
        | tee headlog.txt && \
        [ `wc -l < headlog.txt` = 2 ] || \
        (cat headlog.txt ChangeLog > ChangeLog.tmp && mv ChangeLog{.tmp,}) && \
        git add `git diff --no-prefix -I '^;' | sed -n 's/^--- //p' | grep SKK-JISYO` ChangeLog && \
        printf "auto-push after auto-make\n\n" \
        | cat - headlog.txt \
        | git commit -F - && \
        git push

    - name: upload dicts artifact
      uses: actions/upload-artifact@v4
      with:
        name: dicts
        path: |
          dict/*.gz
          dict/*.md5

    - name: upload source artifact
      uses: actions/upload-artifact@v4
      with:
        name: source
        path: dict

    - name: make wrong_check
      run: |
        cd dict
        make wrong_check
        (for i in *.w; do echo $i; cat $i; echo; done) | nkf -w
